### ISSUE TITLE
Set up HL7 V2 <==> FHIR Translation Mediator

### ISSUE THREAD

**Issue by pmanko** [B-TECHBW/hie-botswana-archived#4]

**Comment by pmanko** [comment]
Some resources at first glance:
- https://confluence.hl7.org/display/OO/2-To-FHIR+Project
- https://build.fhir.org/ig/HL7/v2-to-fhir/
- https://github.com/microsoft/FHIR-Converter
- https://github.com/LinuxForHealth/hl7v2-fhir-converter

- https://smilecdr.com/docs/configuration_categories/hl7v2_fhir_mapper_general.html

**Comment by pmanko** [comment]
Scaffolding for production-ready mediator: 
https://github.com/jembi/openhim-mediator-bootstrap-production/tree/master/src

**Comment by pmanko** [comment]
OpenHIM Mapping Mediator: https://jembi.github.io/openhim-mediator-mapping/docs/gettingStarted/introduction

**Comment by pmanko** [comment]
Shell script mediator (for possible MS Liquid converter integration): https://github.com/jembi/openhim-mediator-shell-script

**Comment by ccwhite333** [comment]
https://jembi.github.io/openhim-mediator-mapping/
